spring.application.name=registration-service
server.port=8083

# Cấu hình JDBC Driver & URL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh

# Thay 'mat_khau_moi_cua_ban' bằng đúng mật khẩu bạn vừa đổi
spring.datasource.username=root
spring.datasource.password=vanh2005

# Khai báo trực tiếp Dialect để tránh lỗi tự động nhận diện metadata
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Đường dẫn gọi sang course-service
course-service.base-url=http://localhost:8082
jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te
jwt.expiration-ms=86400000
