spring.application.name=registration-service
server.port=${SERVER_PORT:8083}

# Cấu hình JDBC Driver & URL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/registration_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vanh2005}

# Khai báo trực tiếp Dialect để tránh lỗi tự động nhận diện metadata
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Đường dẫn gọi sang course-service
course-service.base-url=${COURSE_SERVICE_BASE_URL:http://localhost:8082}
jwt.secret=${JWT_SECRET:CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
