server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        - id: auth-service-apikeys
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/api-keys,/api/api-keys/**
          filters:
            - RewritePath=/api/api-keys/(?<segment>.*), /api-keys/${segment}
            - RewritePath=/api/api-keys, /api-keys

        - id: course-service-list
          uri: ${COURSE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/courses
          filters:
            - RewritePath=/api/courses, /courses

        - id: course-service-detail
          uri: ${COURSE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/courses/**
          filters:
            - RewritePath=/api/courses/(?<segment>.*), /courses/${segment}

        - id: registration-service-list
          uri: ${REGISTRATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/registrations
          filters:
            - RewritePath=/api/registrations, /registrations

        - id: registration-service-detail
          uri: ${REGISTRATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/registrations/**
          filters:
            - RewritePath=/api/registrations/(?<segment>.*), /registrations/${segment}

        - id: course-service-partner
          uri: ${COURSE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/public/courses
          filters:
            - RewritePath=/api/public/courses, /courses

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "http://localhost:5174"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET:CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te}

management:
  endpoints:
    web:
      exposure:
        include: gateway